version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /dashboard
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /dashboard/.vite/deps
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /netperf-1es-syncer
    schedule:
      interval: daily
