name: "Download caller artifacts"
description: "This action runs multiple steps as a composite action."
inputs:
  caller_id:
    description: "The caller id to use for the download."
    type: string
    required: true
  name:
    description: "The name of the artifact to download."
    type: string
    required: true
  path:
    description: "The path to download the artifact to."
    type: string
    required: true
runs:
  using: "composite"
  steps:
  - name: Query for artifact
    run: |
      $github_headers = @{
        "Accept" = "application/vnd.github+json"
        "Authorization" = "Bearer ${{ secrets.GITHUB_TOKEN }}"
        "X-GitHub-Api-Version" = "2022-11-28"
      }
      $github_url = "https://api.github.com/repos/microsoft/netperf/actions/runs/${{ inputs.caller_id }}/artifacts"
      $response = Invoke-WebRequest -Uri $github_url -Headers $github_headers -Method Get
      $artifact = $response.Content | ConvertFrom-Json | Where-Object { $_.name -eq ${{ inputs.name }} }
      if ($artifact -eq $null) {
        Write-Error "Artifact not found."
        exit 1
      }
      $artifact_download_url = $artifact.url 
      $response = Invoke-WebRequest -Uri $artifact_download_url -Headers $github_headers -Method Get -OutFile "${{ inputs.name }}.zip"
      Write-Output "Artifact downloaded successfully!"
