name: "My Composite Action"
description: "This action runs multiple steps as a composite action."
inputs:
  matrix:
    description: "The serialized matrix of values to use for the composite action."
    type: string
    required: true
  syncer_secret:
    description: "The secret to use for the syncer."
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - name: Deserializes the matrix input
      id: deserialize
      run: |
        $matrix = ConvertFrom-Json '${{ inputs.matrix }}'
        $remote_powershell_supported = $matrix.remote_powershell_supported
        $role = $matrix.role
        $env_str = $matrix.env_str
        echo "remote_powershell_supported=$remote_powershell_supported" >> $env:GITHUB_ENV
        echo "role=$role" >> $env:GITHUB_ENV
        echo "env_str=$env_str" >> $env:GITHUB_ENV
      shell: pwsh
    - name: (Client | no remote pwsh) Uploads ACK to remote cache
      if: ${{ env.role == 'client' && env.remote_powershell_supported == 'FALSE' }}
      run: |
        $headers = @{
          "secret" = "${{ inputs.syncer_secret }}"
        }
        Invoke-WebRequest -Uri "https://netperfapi.azurewebsites.net/setkeyvalue?key=${{ github.run_id }}_${{ env.env_str }}_state&value=done" -Headers $headers -Method Post
      shell: pwsh
    - name: (Client | yes remote pwsh) Creates a 'done.txt' file to signal the server
      if: ${{ env.role == 'client' && env.remote_powershell_supported == 'TRUE' }}
      run: |
        $Session = New-PSSession -ComputerName netperf-peer
        Invoke-Command -Session $Session -ScriptBlock {
          New-Item -ItemType File -Name "done.txt" -Path "C:\"
        }
      shell: pwsh

