name: "Stop 1ES Machine"
description: "This action runs multiple steps as a composite action."
inputs:
  matrix:
    description: "The serialized matrix of values to use for the composite action."
    type: string
    required: true
  syncer_secret:
    description: "The secret to use for the syncer."
    type: string
    required: true
runs:
  using: "composite"
  steps:
  - name: Run Python Script to Escape JSON
    if: ${{ env.OS == 'windows' }}
    id: escape_json
    run: |
      import json
      matrix = json.loads("""${{ inputs.matrix }}""")
      json_str = json.dumps(matrix).replace('"', '\\"').replace('\n', ' ').replace('\r', ' ')
      print(f"::set-output name=escaped_json::{json_str}")
    shell: python
  - name: Deserialize Matrix
    if: ${{ env.OS == 'windows' }}
    run: |
      "C:\Program Files\PowerShell\7\pwsh.exe" -Command "./netperfrepo/1es-machine-manager.ps1 -Action 'Deserialize_matrix' -GithubContextInput1 '${{ steps.escape_json.outputs.escaped_json }}'"
    shell: cmd
  - name: Deserialize Matrix
    if: ${{ env.OS != 'windows' }}
    run: |
      ./netperfrepo/1es-machine-manager.sh -Action 'Deserialize_matrix' -GithubContextInput1 '${{ inputs.matrix }}'
  - name: Send ACK to cache
    if: ${{ env.OS == 'windows' }}
    run: |
      "C:\Program Files\PowerShell\7\pwsh.exe" -Command "./netperfrepo/1es-machine-manager.ps1 -Action 'Stop-1es-machine' -GithubContextInput1 '${{ inputs.syncer_secret }}' -GithubContextInput2 '${{ github.run_id }}' -GithubContextInput3 '${{ env.env_str }}'"
    shell: cmd
  - name: Send ACK to cache
    if: ${{ env.OS != 'windows' }}
    run: |
      ./netperfrepo/1es-machine-manager.sh -Action 'Stop-1es-machine' -GithubContextInput1 '${{ inputs.syncer_secret }}' -GithubContextInput2 '${{ github.run_id }}' -GithubContextInput3 '${{ env.env_str }}'
    shell: pwsh
