name: "My Composite Action"
description: "This action runs multiple steps as a composite action."
inputs:
  remote-powershell-supported:
    description: "Whether or not remote powershell is supported"
    required: true
runs:
  using: "composite"
  steps:
    - name: (Client | no remote pwsh) Uploads ACK to remote cache
      if: ${{ matrix.role == 'client' }}
      run: |
        $headers = @{
          "secret" = "${{ secrets.NETPERF_SYNCER_SECRET }}"
        }
        Invoke-WebRequest -Uri "https://netperfapi.azurewebsites.net/setkeyvalue?key=${{ github.run_id }}_${{ matrix.env_str }}_state&value=done" -Headers $headers -Method Post
      shell: pwsh
    - name: (Client | yes remote pwsh) Creates a 'done.txt' file to signal the server
      if: ${{ matrix.role == 'client' && matrix.remote_powershell_supported == 'TRUE' }}
      run: |
        $Session = New-PSSession -ComputerName netperf-peer
        Invoke-Command -Session $Session -ScriptBlock {
          New-Item -ItemType File -Name "done.txt" -Path "C:\"
        }
      shell: pwsh

