name: "Run Pwsh Commands"
description: "This action runs multiple steps as a composite action."
inputs:
  run-cmd:
    description: "The serialized matrix of values to use for the composite action."
    type: string
    required: true
runs:
  using: "composite"
  steps:
  - name: Run Pwsh Command
    if: ${{ env.OS == 'windows' }}
    run: |
      "C:\Program Files\PowerShell\7\pwsh.exe" -Command "${{ inputs.run-cmd }}"
    shell: cmd
  - name: Run Pwsh Command
    if: ${{ env.OS != 'windows' }}
    run: |
      ${{ inputs.run-cmd }}
    shell: pwsh
