name: Custom Tasks

on:
  workflow_dispatch:

permissions: write-all
jobs:
  upload-core-dmp:
    runs-on:
    - self-hosted
    - lab
    - os-ubuntu-20.04
    - x64
    steps:
      - name: Inspect core dump
        run: ls /var/lib/apport/coredump
      - name: Upload core dump
        uses: actions/upload-artifact@v2
        with:
          name: core-dump
          path: /var/lib/apport/coredump/*
      - name: Delete all files in core dump directory
        run: |
          whoami
          sudo rm -rf /var/lib/apport/coredump/*
      - name: Verify deletion
        run: ls /var/lib/apport/coredump
