name: Custom Tasks

on:
  workflow_dispatch:

permissions: write-all

jobs:
  test:
    strategy:
      matrix:
        include: []
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      