name: Custom Tasks

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Windows OS Version'
        required: false
        default: "2022"
        type: choice
        options:
          - "2025"
          - "2022"
          - "2019"

permissions: write-all

jobs:
  testjob:
    needs: []
    strategy:
      matrix:
        role: ["client", "server"]
    runs-on: [self-hosted, 1ES.Pool=netperf-aztestpool-linux]
    steps:
      - name: Get Local Users
        run: |
          pwsh --version
          cat /etc/passwd
        shell: pwsh

      - name: Switch to user secnetperf
        run: |
          sudo su - secnetperf
          whoami
        shell: pwsh

      - name: Who Am I
        run: whoami
        shell: pwsh

      - name: Powershell remoting please
        run: |
          sudo apt-get install -y wget apt-transport-https software-properties-common --allow-change-held-packages
          wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell --allow-change-held-packages
        shell: bash

      - name: (Client) Upload public key to server
        if: ${{ matrix.role == 'client' }}
        run: |
          $headers = @{
            "secret" = "${{ secrets.NETPERF_SYNCER_SECRET }}"
          }
          ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
          $publicKey = Get-Content ~/.ssh/id_rsa.pub
          $uri = "https://netperfapiwebapp.azurewebsites.net/setkeyvalue?key=${{ github.run_id }}_publickey&value=$publicKey"
          Invoke-WebRequest -Uri $uri -Headers $headers
        shell: pwsh

      - name: (Server) Poll for a public key uploaded by the client, set authorized_keys.
        if: ${{ matrix.role == 'server' }}
        run: |
          $found = $false
          $headers = @{
            "secret" = "${{ secrets.NETPERF_SYNCER_SECRET }}"
          }
          $uri = "https://netperfapiwebapp.azurewebsites.net/getkeyvalue?key=${{ github.run_id }}_publickey"
          do {
            Write-Output "Checking for public key..."
            try {
              $Response = Invoke-WebRequest -Uri $uri -Headers $headers
              if (!($Response.StatusCode -eq 200)) {
                throw "Failed to get public key. Status code: $($Response.StatusCode)"
              }
              $publicKey = $Response.Content
              # Run the script
              $authorizedKeysPath = "$HOME/.ssh/authorized_keys"
              Write-Output "Authorized Keys Path: $authorizedKeysPath"
              Write-Output "Adding public key to authorized_keys..."
              echo $publicKey | sudo tee -a $authorizedKeysPath | Out-Null
              Write-Output "Public Key added to authorized_keys"
              sudo chmod 600 $authorizedKeysPath
              sudo chmod 700 $HOME/.ssh
              Write-Output "Permissions set on authorized_keys and .ssh directory"
              $found = $true
            }
            catch {
              Write-Output "Public Key not found: $_"
              Start-Sleep -Seconds 5
            }
          } while (-not $found)
        shell: pwsh

      - name: Init SSH
        run: |
          sudo apt update
          sudo apt install openssh-server
          sudo systemctl start ssh
          sudo systemctl enable ssh
          sudo systemctl status sshd
          sudo systemctl status ssh
        shell: bash

      - name: Configure SSH
        run: |
          echo "Subsystem powershell /usr/bin/pwsh -sshs -NoLogo -NoProfile" | sudo tee -a /etc/ssh/sshd_config
          sudo systemctl restart sshd
          sudo systemctl restart ssh
        shell: bash

      - name: Check SSH
        run: |
          sudo systemctl status sshd
          sudo systemctl status ssh
        shell: bash

      - name: (Server) Upload IP address to shared cache
        if: ${{ matrix.role == 'server' }}
        run: |
          $ipAddress = ip addr | grep 'inet ' | grep '10' | awk '{print $2}' | cut -d'/' -f1
          $headers = @{
            "secret" = "${{ secrets.NETPERF_SYNCER_SECRET }}"
          }
          Invoke-WebRequest -Uri "https://netperfapiwebapp.azurewebsites.net/setkeyvalue?key=${{ github.run_id }}_ipaddress&value=$ipAddress" -Headers $headers
        shell: pwsh

      - name: (Server) Polls for a "done.txt" file from the client
        if: ${{ matrix.role == 'server' }}
        run: |
          $found = $false
          do {
              $donepath = "\var\done.txt"
              Write-Output "Checking for done.txt..."
              if (Test-Path $donepath) {
                Write-Output "done.txt found"
                $found = $true
                break
              } else {
                Write-Output "done.txt not found"
              }

              $StatePath = "\var\_state"
              if (Test-Path $StatePath) {
                ls $StatePath
                # Fetch all files in the _state directory
                $files = Get-ChildItem -Path $StatePath -File
                # Find the highest lexicographically sorted file name
                $max = 0
                foreach ($file in $files) {
                    $filename = $file.Name.split(".")[0]
                    $num = [int]($filename -replace "[^0-9]", "")
                    if ($num -gt $max) {
                        $max = $num
                    }
                }
                # Check if there is a corresponding "completed" file
                $ExecuteFileExist = Test-Path "$StatePath\execute_$($max).ps1"
                $CompletedFileExist = Test-Path "$StatePath\completed_$($max).txt"
                if ($ExecuteFileExist -and !($CompletedFileExist)) {
                    Write-Host "Executing $StatePath\execute_$($max).ps1"
                    Invoke-Expression "$StatePath\execute_$($max).ps1"
                    Write-Host "Creating $StatePath\completed_$($max).txt"
                    New-Item -ItemType File -Name "completed_$($max).txt" -Path $StatePath
                } else {
                    Write-Host "No outstanding script to execute... Highest order script found so far: $max"
                }
              } else {
                Write-Host "State directory not found"
              }
              Start-Sleep -Seconds 10
          } while (-not $found)
        shell: pwsh

      - name: (Client) Poll for an ip address uploaded by the server, set netperf-peer.
        if: ${{ matrix.role == 'client' }}
        run: |
          $found = $false
          $headers = @{
            "secret" = "${{ secrets.NETPERF_SYNCER_SECRET }}"
          }
          $uri = "https://netperfapiwebapp.azurewebsites.net/getkeyvalue?key=${{ github.run_id }}_ipaddress"
          do {
            Write-Output "Checking for ip address..."
            try {
              $Response = Invoke-WebRequest -Uri $uri -Headers $headers
              if (!($Response.StatusCode -eq 200)) {
                throw "Failed to get ip address. Status code: $($Response.StatusCode)"
              }
              $ipAddress = $Response.Content
              Write-Output "Ip Address found: $ipAddress"
              $serverIp = $ipAddress
              Write-Output "Server IP: $serverIp"
              $found = $true
            }
            catch {
              Write-Output "Ip Address not found: $_"
              Start-Sleep -Seconds 5
            }
          } while (-not $found)

          Write-Host "Preparing to run enable remote powershell session"
          echo "$serverIp netperf-peer" | sudo tee -a /etc/hosts

          Write-Host "Adding server IP to hosts file"
          ssh-keyscan -H "netperf-peer" >> $HOME/.ssh/known_hosts

          Write-Host "$(Get-Date) Try starting a remote session"
          Write-Host "Print powershell version information: "
          pwsh --version
          Write-Host "Check sshd_config"
          cat /etc/ssh/sshd_config
          $Session = New-PSSession -HostName netperf-peer -Username secnetperf -SSHTransport
          $Session
        shell: pwsh

      - name: (Client) Creates a 'done.txt' file to signal the server
        if: ${{ matrix.role == 'client' }}
        run: |
          $Session = New-PSSession -HostName netperf-peer -UserName secnetperf -SSHTransport
          Invoke-Command -Session $Session -ScriptBlock {
            New-Item -ItemType File -Name "done.txt" -Path "C:\"
          }
        shell: pwsh
