name: Unblock Lab Machine

on:
  workflow_dispatch:
    inputs:
      parent-id:
        description: 'The ID of the parent lab machine (RR1-Netperf-43...etc.)'
        required: true
        type: string

permissions: write-all

jobs:
  unblock-job:
    runs-on: windows-latest
    steps:
      - name: Set parent id to 'DONE' on remote cache
        run: |
          $headers = @{
            "secret" = "${{ secrets.NETPERF_SYNCER_SECRET }}"
          }
          $parentApi = "https://netperfapi.azurewebsites.net/setkeyvalue?key=${{ inputs.parent-id }}&value=FORCEUNBLOCK"
        shell: pwsh
